version: 0.0
Resources:
- TargetService:
    Type: AWS::ECS::Service
    properties:
      TaskDefinition: "arn:aws:ecs:ap-south-1:533267334695:task-definition/endgame-backend-terraform"
      LoadBalancerInfo:
        ContainerName: "backend"
        ContainerPort: 5000
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: ["subnet-0d6e3204117daa85e", "subnet-062f87d0cfba1b2f0"]
          SecurityGroups: ["sg-0f31a62ffed0fbf3d"]
- TargetService:
    Type: AWS::ECS::Service
    properties:
      TaskDefinition: "arn:aws:ecs:ap-south-1:533267334695:task-definition/endgame-frontend-terraform"
      LoadBalancerInfo:
        ContainerName: "frontend"
        ContainerPort: 5000
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: ["subnet-0d6e3204117daa85e", "subnet-062f87d0cfba1b2f0"]
          SecurityGroups: ["sg-0f31a62ffed0fbf3d"]
          # AssignPublicIp: "ENABLED"


